version: '2'

services:
  apigw:
    image: hub.fileserver.com/filestore/apigw
    network_mode: host
#    networks:
#      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    # 区分traefik能力
    labels:
      - "traefik.backend=apigw"
      - "traefik.frontend.rule=Host:apigw.fileserver.com"
      - "traefik.docker.port=8080"

  upload:
    image: hub.fileserver.com/filestore/upload
    network_mode: host
#    networks:
#      - web
    volumes:
      - /data/fileserver:/data/fileserver
      - /data/fileserver_part:/data/fileserver_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=upload"
      - "traefik.frontend.rule=Host:upload.fileserver.com"
      - "traefik.docker.port=28080"

  download:
    image: hub.fileserver.com/filestore/download
    network_mode: host
#    networks:
#      - web
    volumes:
      - /data/fileserver:/data/fileserver
      - /data/fileserver_part:/data/fileserver_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=download"
      - "traefik.frontend.rule=Host:download.fileserver.com"
      - "traefik.docker.port=38080"

  account:
    image: hub.fileserver.com/filestore/account
    network_mode: host
#    networks:
#      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}

  transfer:
    image: hub.fileserver.com/filestore/transfer
    network_mode: host
#    networks:
#      - web
    volumes:
      - /data/fileserver:/data/fileserver
      - /data/fileserver_part:/data/fileserver_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}

  dbproxy:
    image: hub.fileserver.com/filestore/dbproxy
    network_mode: host
#    networks:
#      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}

#networks:
#  web:
#    external:
#      name:

