version: '3'

services:
  apigw:
    image: hub.fileserver.com/filestore/apigw
    networks:
      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    # 区分traefik能力
    labels:
      - traefik.backend=apigw
      - traefik.http.routers.dc_compose_apigw_1.rule=Host(`apigw.fileserver.com`)
      - traefik.http.services.dc_compose_apigw_1.loadbalancer.server.port=8080

  upload:
    image: hub.fileserver.com/filestore/upload
    networks:
      - web
    volumes:
      - /data/fileserver:/data/fileserver
      - /data/fileserver_part:/data/fileserver_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=upload"
      - "traefik.http.routers.dc_compose_upload_1.rule=Host(`upload.fileserver.com`)"
      - "traefik.http.services.dc_compose_upload_1.loadbalancer.server.port=28080"
#
  download:
    image: hub.fileserver.com/filestore/download
    networks:
      - web
    volumes:
      - /data/fileserver:/data/fileserver
      - /data/fileserver_part:/data/fileserver_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}
    labels:
      - "traefik.backend=download"
      - "traefik.http.routers.dc_compose_download_1.rule=Host(`download.fileserver.com`)"
      - "traefik.http.services.dc_compose_download_1.loadbalancer.server.port=38080"
#
  account:
    image: hub.fileserver.com/filestore/account
    networks:
      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}

  transfer:
    image: hub.fileserver.com/filestore/transfer
    networks:
      - web
    volumes:
      - /data/fileserver:/data/fileserver
      - /data/fileserver_part:/data/fileserver_part
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}

  dbproxy:
    image: hub.fileserver.com/filestore/dbproxy
    networks:
      - web
    env_file:
      - ./.env
    environment:
      - PARAMS=${registryAddr} ${redisAddr} ${mysqlAddr} ${mqAddr}

networks:
  web:
    external:
      name: fileserver

